version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: launchpadapi_app
    container_name: launchpadapi_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - launchpadapi-network
    ports:
      - "9000:9000"

  web:
    image: nginx:alpine
    container_name: launchpadapi_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - launchpadapi-network

networks:
  launchpadapi-network:
    driver: bridge
